### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lena-schneider-fotografie** [lena-schneider-fotografie/lena-schneider-fotografie.github.io#1]
- [ ] Texte fertig schreiben:
  - [ ] Abläufe
  - [ ] Paketinhalt
  - [ ] Über mich unten
- [ ] Social links
- [ ] Projects in Pakete umbenennen (Kevin)
- [ ] Hauptfarbe anpassen
- [ ] Bilder:
  - [ ] Newborn paket
  - [ ] Fußleiste
- [ ] Blog post samples entfernen (Kevin)
- [ ] Testimonials: Anna, Jenny, Martina
